# Generated by Django 5.2.12 on 2026-04-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='capcacidade',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
