# Generated by Django 5.2.12 on 2026-04-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_veiculo_capcacidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('KG', 'Quilogramas'), ('TON', 'Toneladas'), ('G', 'Gramas')], default='KG', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capcacidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
