# Generated by Django 5.2.12 on 2026-04-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carga_alter_motorista_cnh_alter_veiculo_capcacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='moeda',
            field=models.CharField(choices=[('KG', 'Quilogramas'), ('TON', 'Toneladas'), ('G', 'Gramas')], default='Reais', max_length=3),
        ),
    ]
