# Generated by Django 5.2.12 on 2026-04-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_carga_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='moeda',
            field=models.CharField(choices=[('Reais', 'Reais'), ('Euro', 'Euros'), ('Dolar', 'Dólares')], default='Reais', max_length=5),
        ),
    ]
