# Generated by Django 5.2.12 on 2026-04-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_carga_moeda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_inicial', models.CharField(max_length=150)),
                ('ponto_final', models.CharField(max_length=150)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
