# Generated by Django 5.2.12 on 2026-04-07 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('carga', models.ForeignKey(db_column='id_carga', on_delete=django.db.models.deletion.CASCADE, to='core.carga')),
                ('motorista', models.ForeignKey(db_column='id_motorista', on_delete=django.db.models.deletion.CASCADE, to='core.motorista')),
                ('rota', models.ForeignKey(db_column='id_rota', on_delete=django.db.models.deletion.CASCADE, to='core.rota')),
                ('veiculo', models.ForeignKey(db_column='id_veiculo', on_delete=django.db.models.deletion.CASCADE, to='core.veiculo')),
            ],
        ),
    ]
