# Generated by Django 5.2.12 on 2026-04-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_frete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frete',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='origem',
        ),
    ]
