# Generated by Django 5.2.12 on 2026-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_frete_destino_remove_frete_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='moeda',
            field=models.CharField(choices=[('Reais', 'Reais'), ('Euro', 'Euros'), ('Dolar', 'Dólares')], default='Reais', max_length=5),
        ),
    ]
