# Generated by Django 5.2.12 on 2026-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_frete_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
