# Generated by Django 5.2.12 on 2026-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_motorista_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cargas/'),
        ),
    ]
