# Generated by Django 5.2.12 on 2026-05-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_carga_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frete',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fretes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
