# Generated by Django 5.2.12 on 2026-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_carga_usuario_frete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='ultima_localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
