# Generated by Django 5.2.12 on 2026-06-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_frete_ultima_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
