# Generated by Django 5.2.12 on 2026-07-01 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_frete_latitude_frete_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
