# Generated by Django 5.2.12 on 2026-07-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rota_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='distancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
