# Generated by Django 5.2.12 on 2026-07-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_rota_distancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='distancia',
        ),
    ]
