# Generated by Django 5.2.12 on 2026-09-09 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_rota_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
