# Generated by Django 5.2.12 on 2026-10-06 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_motorista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
